### ISSUE TITLE
A simple comment

### ISSUE THREAD

**Issue by Jean-pierre14** [Sanika2103/myportfolio#3]
**Thank you**. **Dear developer I would like to suggest you to change you HTML header code to this**

1. <head>
2.     <meta charset="UTF-8">
3.     <meta http-equiv="X-UA-Compatible" content="IE=edge">
4.     <meta name="viewport" content="width=device-width, initial-scale=1.0">
5.     <link rel="stylesheet" href="./portfolio.css">
6.     <title>Portfolio</title>
7. </head>

and also and the responsive size. because in mobile people cannot see you name or if you want copy the following code within your portfolio.css

------

1. @media(max-width: 600px) {
2.         * {
3.             margin: 0;
4.             padding: 0;
5.             box-sizing: border-box;
6.         }
7.         .main {
8.             position: relative;
9.             display: block;
10.             width: 100%;
11.             padding: 0;
12.         }
13.         .cat {
14.             position: relative;
15.             margin: 0;
16.             padding: 0;
17.         }
18.         .project-title {
19.             position: relative;
20.             padding: 0;
21.             margin: 0;
22.         }
23.         .navbar {
24.             padding: 0;
25.             margin: 0;
26.             display: block;
27.             width: 100%;
28.         }
29.         .nav-item {
30.             display: block;
31.             position: relative;
32.             width: 100%;
33.         }
34.         .nav-item ul {
35.             display: block;
36.         }
37.         .nav-item ul li {
38.             width: 100%;
39.         }
40.         .nav-item ul li a {
41.             display: block;
42.             width: 100%;
43.             text-align: center;
44.             background: chocolate;
45.             /* padding: 10px; */
46.         }
47.         .project {
48.             position: relative;
49.             width: 100%;
50.             display: grid;
51.             grid-template-columns: 1fr;
52.         }
53.     }
54. 

------

**Comment by Sanika2103** [comment]
Thank you . I'll surely take care of all changes.

**Comment by Jean-pierre14** [comment]
Thank you too to trust in me
